<a href="https://colab.research.google.com/github/yaarsuraj/numpy/blob/main/numpy_tutor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import time

In [ ]:
size = 1_000_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

np.arr = np.array(py_list)
start = time.time()
sq_array = np.arr ** 2
end = time.time()
print(f"python Array time = {end-start} seconds")

python list time = 0.07375001907348633 seconds
python Array time = 0.0016770362854003906 seconds


In [ ]:
#memory
import sys
print(f"python list size = {sys.getsizeof(sq_list)} bytes")
print(f"python array size = {np.arr.nbytes} bytes")

python list size = 8448728 bytes
python array size = 8000000 bytes


In [ ]:
#create - from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
#create
arr1 = np.zeros((2,3), dtype="int64") #prefill
print(arr1, arr1.shape)
arr2 = np.ones((2,3), dtype="int64") #prefill
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye((3)) #identity matrix
print(arr4, arr4.shape)

#range(start, end, stop)
arr5 = np.arange(0, 100) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(0, 10, 3) #evenly spaced arrays (start, stop, number of points)
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] (100,)
[ 0.  5. 10.] (3,)


In [ ]:
#properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)
print(arr.size)

float_arr = arr.astype(np.float64)
print(float_arr)

(3, 3)
9
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
#operations on array
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)


flattened = arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [ ]:
#indexing
arr = np.array([1, 2, 3, 4 , 5])
print(arr[0])
print(arr[4])

1
5


In [ ]:
#slicing
arr = np.array([1,2,3,4,5])
#[start, end, step]

print(arr[1:4])

[2 3 4]


In [ ]:
import numpy as np
#data types
arr = np.array([1,2,3,4,5])
print(arr, arr.dtype)

[1 2 3 4 5] int64
